core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.classes import *
from core.views import *

app_name = "core"


urlpatterns = [
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag_autocomplete'),
    # path('players/', player_by_club_json, name='player_by_club'),

    path('login/', LogInView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('', backend_index, name="backend_index"),


    path('stadiums/', list_stadium, name='stadium_list'),
    path('stadiums/data_table/', login_required(StadiumListJson.as_view()), name='stadium_data_table'),
    path('stadiums/edit/<item_id>/', edit_stadium, name='stadium_edit'),
    path('stadiums/delete/<item_id>/', delete_stadium, name='stadium_delete'),
    path('stadiums/create/', create_stadium, name='stadium_create'),

    path('seasons/', list_season, name='season_list'),
    path('seasons/data_table/', login_required(SeasonListJson.as_view()), name='season_data_table'),
    path('seasons/edit/<item_id>/', edit_season, name='season_edit'),
    path('seasons/delete/<item_id>/', delete_season, name='season_delete'),
    path('seasons/create/', create_season, name='season_create'),

    path('positions/', list_position, name='position_list'),
    path('positions/data_table/', login_required(PositionListJson.as_view()), name='position_data_table'),
    path('positions/edit/<item_id>/', edit_position, name='position_edit'),
    path('positions/delete/<item_id>/', delete_position, name='position_delete'),
    path('positions/create/', create_position, name='position_create'),


    path('leagues/', list_league, name='league_list'),
    path('leagues/data_table/', login_required(LeagueListJson.as_view()), name='league_data_table'),
    path('leagues/edit/<item_id>/', edit_league, name='league_edit'),
    path('leagues/delete/<item_id>/', delete_league, name='league_delete'),
    path('leagues/create/', create_league, name='league_create'),

    path('clubs/', list_club, name='club_list'),
    path('clubs/data_table/', login_required(ClubListJson.as_view()), name='club_data_table'),
    path('clubs/edit/<item_id>/', edit_club, name='club_edit'),
    path('clubs/delete/<item_id>/', delete_club, name='club_delete'),
    path('clubs/create/', create_club, name='club_create'),

    path('players/', list_player, name='player_list'),
    path('players/data_table/', login_required(PlayerListJson.as_view()), name='player_data_table'),
    path('players/edit/<item_id>/', edit_player, name='player_edit'),
    path('players/delete/<item_id>/', delete_player, name='player_delete'),
    path('players/create/', create_player, name='player_create'),

    path('player_histories/', list_player_history, name='player_history_list'),
    path('player_histories/data_table/', login_required(PlayerHistoryListJson.as_view()), name='player_history_data_table'),
    path('player_histories/delete/<item_id>/', delete_player_history, name='player_history_delete'),


    path('referees/', list_referee, name='referee_list'),
    path('referees/data_table/', login_required(RefereeListJson.as_view()), name='referee_data_table'),
    path('referees/edit/<item_id>/', edit_referee, name='referee_edit'),
    path('referees/delete/<item_id>/', delete_referee, name='referee_delete'),
    path('referees/create/', create_referee, name='referee_create'),

    path('coaches/', list_coach, name='coach_list'),
    path('coaches/data_table/', login_required(CoachListJson.as_view()), name='coach_data_table'),
    path('coaches/edit/<item_id>/', edit_coach, name='coach_edit'),
    path('coaches/delete/<item_id>/', delete_coach, name='coach_delete'),
    path('coaches/create/', create_coach, name='coach_create'),

    path('coach_histories/', list_coach_history, name='coach_history_list'),
    path('coach_histories/data_table/', login_required(CoachHistoryListJson.as_view()), name='coach_history_data_table'),
    path('coach_histories/delete/<item_id>/', delete_coach_history, name='coach_history_delete'),

    path('matches/', list_match, name='match_list'),
    path('matches/data_table/', login_required(MatchListJson.as_view()), name='match_data_table'),
    path('matches/edit/<item_id>/', edit_match, name='match_edit'),
    path('matches/delete/<item_id>/', delete_match, name='match_delete'),
    path('matches/create/', create_match, name='match_create'),

    path('match_details/', list_match_detail, name='match_detail_list'),
    path('match_details/data_table/', login_required(MatchDetailListJson.as_view()), name='match_detail_data_table'),
    path('match_details/edit/<item_id>/', edit_match_detail, name='match_detail_edit'),
    path('match_details/delete/<item_id>/', delete_match_detail, name='match_detail_delete'),
    path('match_details/create/', create_match_detail, name='match_detail_create'),


    path('match_actions/', list_match_action, name='match_action_list'),
    path('match_actions/data_table/', login_required(MatchActionListJson.as_view()), name='match_action_data_table'),
    path('match_actions/edit/<item_id>/', edit_match_action, name='match_action_edit'),
    path('match_actions/delete/<item_id>/', delete_match_action, name='match_action_delete'),
    path('match_actions/create/', create_match_action, name='match_action_create'),


    path('categories/', list_category, name='category_list'),
    path('categories/data_table/', login_required(CategoryListJson.as_view()), name='category_data_table'),
    path('categories/edit/<item_id>/', edit_category, name='category_edit'),
    path('categories/delete/<item_id>/', delete_category, name='category_delete'),
    path('categories/create/', create_category, name='category_create'),

    path('posts/', list_post, name='post_list'),
    path('posts/data_table/', login_required(PostListJson.as_view()), name='post_data_table'),
    path('posts/edit/<item_id>/', edit_post, name='post_edit'),
    path('posts/delete/<item_id>/', delete_post, name='post_delete'),
    path('posts/create/', create_post, name='post_create'),

    path('banners/', list_banner, name='banner_list'),
    path('banners/data_table/', login_required(BannerListJson.as_view()), name='banner_data_table'),
    path('banners/edit/<item_id>/', edit_banner, name='banner_edit'),
    path('banners/delete/<item_id>/', delete_banner, name='banner_delete'),
    path('banners/create/', create_banner, name='banner_create'),

    path('banner_positions/', list_banner_position, name='banner_position_list'),
    path('banner_positions/data_table/', login_required(BannerPositionListJson.as_view()), name='banner_position_data_table'),
    path('banner_positions/edit/<item_id>/', edit_banner_position, name='banner_position_edit'),
    path('banner_positions/delete/<item_id>/', delete_banner_position, name='banner_position_delete'),
    path('banner_positions/create/', create_banner_position, name='banner_position_create'),

    path('galleries/', list_gallery, name='gallery_list'),
    path('galleries/data_table/', login_required(GalleryListJson.as_view()), name='gallery_data_table'),
    path('galleries/edit/<item_id>/', edit_gallery, name='gallery_edit'),
    path('galleries/delete/<item_id>/', delete_gallery, name='gallery_delete'),
    path('galleries/create/', create_gallery, name='gallery_create'),

    path('sponsors/', list_sponsor, name='sponsor_list'),
    path('sponsors/data_table/', login_required(SponsorListJson.as_view()), name='sponsor_data_table'),
    path('sponsors/edit/<item_id>/', edit_sponsor, name='sponsor_edit'),
    path('sponsors/delete/<item_id>/', delete_sponsor, name='sponsor_delete'),
    path('sponsors/create/', create_sponsor, name='sponsor_create'),

    path('socials/', list_social, name='social_list'),
    path('socials/data_table/', login_required(SocialListJson.as_view()), name='social_data_table'),
    path('socials/edit/<item_id>/', edit_social, name='social_edit'),
    path('socials/delete/<item_id>/', delete_social, name='social_delete'),
    path('socials/create/', create_social, name='social_create'),

]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from filebrowser.sites import site

from project import settings

urlpatterns = [
    path('select2/', include('django_select2.urls')),
    path('admin/filebrowser/', site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('ckeditor/', include('core.ckeditor_uploader')),
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('core/', include('core.urls')),
    path('', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/views.py
from django.contrib.auth import logout
from django.core import serializers
from django.http import HttpResponse
from core.helpers import *
from core.models import *


def player_by_club_json(request):

    home_club_id = request.GET.get('home_club_id')
    away_club_id = request.GET.get('away_club_id')

    if home_club_id and away_club_id:
        data = Player.objects.filter(club_id__in=(home_club_id, away_club_id))
        data = serializers.serialize('json', list(data), fields=('name',))
        return HttpResponse(data, content_type='application/json')


def backend_index(request):
    if not request.user.is_authenticated:
        return redirect(reverse_lazy('core:login'))

    matches = get_match_for_current_season()

    return render(request, 'core/index.html', {
        'match_number': matches.count(),
        'player_number': Player.objects.count(),
        'club_number': Club.objects.count(),
        'user_number': User.objects.count(),
    })


def log_out(request):
    logout(request)
    return redirect(reverse_lazy('core:login'))


def list_stadium(request):
    return list_content(request, 'stadium')


def edit_stadium(request, item_id):
    return edit_content(request, 'stadium', item_id)


def create_stadium(request):
    return create_content(request, 'stadium')


def delete_stadium(request, item_id):
    return delete_content(request, 'stadium', item_id)


def list_season(request):
    return list_content(request, 'season')


def edit_season(request, item_id):
    return edit_content(request, 'season', item_id)


def create_season(request):
    return create_content(request, 'season')


def delete_season(request, item_id):
    return delete_content(request, 'season', item_id)


def list_position(request):
    return list_content(request, 'position')


def edit_position(request, item_id):
    return edit_content(request, 'position', item_id)


def create_position(request):
    return create_content(request, 'position')


def delete_position(request, item_id):
    return delete_content(request, 'position', item_id)


def list_league(request):
    return list_content(request, 'league')


def edit_league(request, item_id):
    return edit_content(request, 'league', item_id)


def create_league(request):
    return create_content(request, 'league')


def delete_league(request, item_id):
    return delete_content(request, 'league', item_id)


def list_club(request):
    return list_content(request, 'club')


def edit_club(request, item_id):
    return edit_content(request, 'club', item_id)


def create_club(request):
    return create_content(request, 'club')


def delete_club(request, item_id):
    return delete_content(request, 'club', item_id)


def list_player(request):
    return list_content(request, 'player')


def edit_player(request, item_id):
    return edit_content(request, 'player', item_id)


def create_player(request):
    return create_content(request, 'player')


def delete_player(request, item_id):
    return delete_content(request, 'player', item_id)


def list_player_history(request):
    return list_content(request, 'player_history')


def delete_player_history(request, item_id):
    return delete_content(request, 'player_history', item_id)


def list_referee(request):
    return list_content(request, 'referee')


def edit_referee(request, item_id):
    return edit_content(request, 'referee', item_id)


def create_referee(request):
    return create_content(request, 'referee')


def delete_referee(request, item_id):
    return delete_content(request, 'referee', item_id)


def list_coach(request):
    return list_content(request, 'coach')


def edit_coach(request, item_id):
    return edit_content(request, 'coach', item_id)


def create_coach(request):
    return create_content(request, 'coach')


def delete_coach(request, item_id):
    return delete_content(request, 'coach', item_id)


def list_coach_history(request):
    return list_content(request, 'coach_history')


def delete_coach_history(request, item_id):
    return delete_content(request, 'coach_history', item_id)


def list_match(request):
    return list_content(request, 'match')


def edit_match(request, item_id):
    return edit_content(request, 'match', item_id)


def create_match(request):
    return create_content(request, 'match')


def delete_match(request, item_id):
    return delete_content(request, 'match', item_id)


def list_match_detail(request):
    return list_content(request, 'match_detail')


def edit_match_detail(request, item_id):
    return edit_content(request, 'match_detail', item_id)


def create_match_detail(request):
    return create_content(request, 'match_detail')


def delete_match_detail(request, item_id):
    return delete_content(request, 'match_detail', item_id)


def list_match_action(request):
    return list_content(request, 'match_action')


def edit_match_action(request, item_id):
    return edit_content(request, 'match_action', item_id)


def create_match_action(request):
    return create_content(request, 'match_action')


def delete_match_action(request, item_id):
    return delete_content(request, 'match_action', item_id)


def list_category(request):
    return list_content(request, 'category')


def edit_category(request, item_id):
    return edit_content(request, 'category', item_id)


def create_category(request):
    return create_content(request, 'category')


def delete_category(request, item_id):
    return delete_content(request, 'category', item_id)


def list_post(request):
    return list_content(request, 'post')


def edit_post(request, item_id):
    return edit_content(request, 'post', item_id)


def create_post(request):
    return create_content(request, 'post')


def delete_post(request, item_id):
    return delete_content(request, 'post', item_id)


def list_banner(request):
    return list_content(request, 'banner')


def edit_banner(request, item_id):
    return edit_content(request, 'banner', item_id)


def create_banner(request):
    return create_content(request, 'banner')


def delete_banner(request, item_id):
    return delete_content(request, 'banner', item_id)


def list_banner_position(request):
    return list_content(request, 'banner_position')


def edit_banner_position(request, item_id):
    return edit_content(request, 'banner_position', item_id)


def create_banner_position(request):
    return create_content(request, 'banner_position')


def delete_banner_position(request, item_id):
    return delete_content(request, 'banner_position', item_id)


def list_social(request):
    return list_content(request, 'social')


def edit_social(request, item_id):
    return edit_content(request, 'social', item_id)


def create_social(request):
    return create_content(request, 'social')


def delete_social(request, item_id):
    return delete_content(request, 'social', item_id)


def list_sponsor(request):
    return list_content(request, 'sponsor')


def edit_sponsor(request, item_id):
    return edit_content(request, 'sponsor', item_id)


def create_sponsor(request):
    return create_content(request, 'sponsor')


def delete_sponsor(request, item_id):
    return delete_content(request, 'sponsor', item_id)


def list_gallery(request):
    return list_content(request, 'gallery')


def edit_gallery(request, item_id):
    return edit_content(request, 'gallery', item_id)


def create_gallery(request):
    return create_content(request, 'gallery')


def delete_gallery(request, item_id):
    return delete_content(request, 'gallery', item_id)

core/templates/core/banner/edit.html
{% extends 'core/base.html' %}
{% load static i18n core_helper countries %}

{% block styles %}
    <!-- Plugins css-->
    <link href="{% static "core/ubold/assets/plugins/bootstrap-tagsinput/css/bootstrap-tagsinput.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/switchery/css/switchery.min.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/multiselect/css/multi-select.css" %}"  rel="stylesheet" type="text/css" />
    <link href="{% static "core/ubold/assets/plugins/select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
    <link href="{% static "core/ubold/assets/plugins/bootstrap-select/css/bootstrap-select.min.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/bootstrap-touchspin/css/jquery.bootstrap-touchspin.min.css" %}" rel="stylesheet" />
    <link href="{% static "core/ubold/assets/plugins/bootstrap-datepicker/css/bootstrap-datepicker.min.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">
                <a href="{% url 'core:banner_list' %}" class="btn btn-primary waves-effect waves-light"><span class="m-r-5"><i class="fa fa-list"></i></span> List</a>
            </div>
            <h4 class="page-title">Chi tiết Banner</h4>

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">

            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12">
                        <form method="post" class="form-horizontal" id="edit_form" novalidate enctype="multipart/form-data">
                            {% csrf_token %}
                            {% include 'core/common/form.html' with form=form %}
                            <div class="form-group">
                                <label class="col-sm-3 control-label no-padding-right"></label>
                                <div class="col-sm-9">
                                    <button type="submit" class="btn btn-success waves-effect waves-light">Lưu</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script src="{% static "core/ubold/assets/plugins/bootstrap-tagsinput/js/bootstrap-tagsinput.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/switchery/js/switchery.min.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/multiselect/js/jquery.multi-select.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/jquery-quicksearch/jquery.quicksearch.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/select2/js/select2.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-select/js/bootstrap-select.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-filestyle/js/bootstrap-filestyle.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-touchspin/js/jquery.bootstrap-touchspin.min.js" %}" type="text/javascript"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %}" type="text/javascript"></script>

    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/jquery.mockjax.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/jquery.autocomplete.min.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/plugins/autocomplete/countries.js" %}"></script>
    <script type="text/javascript" src="{% static "core/ubold/assets/pages/autocomplete.js" %}"></script>

    <script src="{% static "core/ubold/assets/plugins/moment/moment.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/timepicker/bootstrap-timepicker.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %}"></script>

{% endblock %}
{% block inline_scripts %}



    <script>

        // Default

        var elems = Array.prototype.slice.call(document.querySelectorAll('#edit_form input[type="checkbox"]'));

        // if-else statement used only for fixing <IE9 issues
        if (Array.prototype.forEach) {

            elems.forEach(function(html) {
                var switchery = new Switchery(html);
            });
        } else {

            for (var i = 0; i < elems.length; i++) {
                var switchery = new Switchery(elems[i]);
            }
        }

        (function($){
            $('#edit_form select').select2();
            $(":file").filestyle({input: false});

            $("#id_dob").datepicker();

        })(jQuery);
    </script>

{% endblock %}

core/templates/core/banner/index.html
{% extends 'core/base.html' %}
{% load static i18n core_helper countries %}
{% block inline_styles %}
    <style>
        .select2-container--default {
            width: 250px !important;
        }
        .select2-container--default .select2-results > .select2-results__options {
            max-height: 500px;
            min-height: 400px;
            overflow-y: auto;
        }
    </style>

{% endblock %}

{% block styles %}
    <!-- DataTables -->
    <link href="{% static "core/ubold/assets/plugins/datatables/jquery.dataTables.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/buttons.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/fixedHeader.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/responsive.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/scroller.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/dataTables.colVis.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/dataTables.bootstrap.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/datatables/fixedColumns.dataTables.min.css" %}" rel="stylesheet" type="text/css"/>
    <link href="{% static "core/ubold/assets/plugins/select2/css/select2.min.css" %}" rel="stylesheet" type="text/css" />
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <div class="btn-group pull-right m-t-15">
                <a href="{% url 'core:banner_create' %}"><button type="button" class="btn btn-default dropdown-toggle waves-effect" >Tạo mới <span class="m-l-5"><i class="fa fa-plus"></i></span></button></a>
            </div>
            <h4 class="page-title">Banners</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <div class="card-box">
                <div class="row">
                    <div class="col-sm-12">
                        <form class="form-inline" role="form" id="search-form">
                            {% csrf_token %}

                            <div class="form-group m-l-10">
                                <label class="sr-only" for="">Search By Name</label>
                                <input type="text" class="form-control" placeholder="Tên" name="name"/>
                            </div>

                            {% get_banner_positions as banner_positions %}
                            <div class="form-group m-l-10">
                                <label class="sr-only" for="">Positions</label>
                                <select name="position" class="form-control select2">
                                    <option value="">Choose Position</option>
                                    {% for position in banner_positions %}
                                        <option value="{{ position.id }}">{{ position.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>

                            <div class="form-group m-l-10">
                                <label class="sr-only" for="">Status</label>
                                <select name="status" class="form-control select2">
                                    <option value="1">Active</option>
                                    <option value="0">Inactive</option>
                                </select>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12">
            <div class="card-box table-responsive">
                <p class="text-muted font-13 m-b-30"></p>
                    <table id="dataTables" class="table table-striped table-bordered table-actions-bar">
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>Link</th>
                                <th>Image</th>
                                <th>Position</th>
                                <th>Status</th>
                                <th>Update At</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                    </table>

            </div>
        </div>
    </div>

{% endblock %}

{% block scripts %}
    <script src="{% static "core/ubold/assets/plugins/datatables/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.bootstrap.js" %}"></script>

    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.bootstrap.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/jszip.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/pdfmake.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/vfs_fonts.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.html5.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/buttons.print.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.fixedHeader.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.keyTable.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.responsive.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/responsive.bootstrap.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.scroller.min.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.colVis.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/datatables/dataTables.fixedColumns.min.js" %}"></script>

    <script src="{% static "core/ubold/assets/pages/datatables.init.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/select2/js/select2.full.min.js" %}"></script>
    <script src="{% static "core/js/handlebars.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/moment/moment.js" %}"></script>
    <script src="{% static "core/ubold/assets/plugins/bootstrap-daterangepicker/daterangepicker.js" %}"></script>
{% endblock %}

{% block inline_scripts %}
    <script type="text/javascript">
        $('.select2').select2();

        $(function () {
            let dataTable = $("#dataTables").DataTable({
                searching: false,
                serverSide: true,
                processing: true,
                ajax: {
                    url: '{% url 'core:banner_data_table' %}',
                    data: function (d) {
                        d.name = $('input[name=name]').val();
                        d.status = $('select[name=status]').val();
                        d.position = $('select[name=position]').val();
                    }
                },
                columns: [
                    {data: 'name', name: 'name', orderable: true},
                    {data: 'link', name: 'link', orderable: true},
                    {data: 'image', name: 'image', orderable: true},
                    {data: 'position', name: 'position', orderable: true},
                    {data: 'status', name: 'status', orderable: false},
                    {data: 'updated_at', name: 'updated_at', orderable: false},
                    {data: 'action', name: 'action', orderable: false},
                ],
                order: [[1, 'desc']]
            });

            $('#search-form input,select').on('change', function(e) {
                e.preventDefault();
                dataTable.draw();
            });

            dataTable.on('click', '[id^="btn-delete-"]', function (e) {
                e.preventDefault();

                let url = $(this).data('url');

                swal({
                    title: "Bạn có muốn xóa?",
                    text: "",
                    type: "warning",
                    showCancelButton: true,
                    confirmButtonColor: "#DD6B55",
                    confirmButtonText: "Accept!"
                }).then(function () {
                    $.ajax({
                        url : url,
                        type : 'GET',
                    }).always(function (data) {
                        dataTable.draw();
                    });
                });
            });
        });
    </script>
{% endblock %}