core/urls.py
from django.contrib.auth.decorators import login_required
from django.urls import path

from core.classes import *
from core.views import *

app_name = "core"


urlpatterns = [
    path('tag-autocomplete/', TagAutoComplete.as_view(), name='tag_autocomplete'),
    # path('players/', player_by_club_json, name='player_by_club'),

    path('login/', LogInView.as_view(), name='login'),
    path('logout/', log_out, name='logout'),
    path('', backend_index, name="backend_index"),


    path('stadiums/', list_stadium, name='stadium_list'),
    path('stadiums/data_table/', login_required(StadiumListJson.as_view()), name='stadium_data_table'),
    path('stadiums/edit/<item_id>/', edit_stadium, name='stadium_edit'),
    path('stadiums/delete/<item_id>/', delete_stadium, name='stadium_delete'),
    path('stadiums/create/', create_stadium, name='stadium_create'),

    path('seasons/', list_season, name='season_list'),
    path('seasons/data_table/', login_required(SeasonListJson.as_view()), name='season_data_table'),
    path('seasons/edit/<item_id>/', edit_season, name='season_edit'),
    path('seasons/delete/<item_id>/', delete_season, name='season_delete'),
    path('seasons/create/', create_season, name='season_create'),

    path('positions/', list_position, name='position_list'),
    path('positions/data_table/', login_required(PositionListJson.as_view()), name='position_data_table'),
    path('positions/edit/<item_id>/', edit_position, name='position_edit'),
    path('positions/delete/<item_id>/', delete_position, name='position_delete'),
    path('positions/create/', create_position, name='position_create'),


    path('leagues/', list_league, name='league_list'),
    path('leagues/data_table/', login_required(LeagueListJson.as_view()), name='league_data_table'),
    path('leagues/edit/<item_id>/', edit_league, name='league_edit'),
    path('leagues/delete/<item_id>/', delete_league, name='league_delete'),
    path('leagues/create/', create_league, name='league_create'),

    path('clubs/', list_club, name='club_list'),
    path('clubs/data_table/', login_required(ClubListJson.as_view()), name='club_data_table'),
    path('clubs/edit/<item_id>/', edit_club, name='club_edit'),
    path('clubs/delete/<item_id>/', delete_club, name='club_delete'),
    path('clubs/create/', create_club, name='club_create'),

    path('players/', list_player, name='player_list'),
    path('players/data_table/', login_required(PlayerListJson.as_view()), name='player_data_table'),
    path('players/edit/<item_id>/', edit_player, name='player_edit'),
    path('players/delete/<item_id>/', delete_player, name='player_delete'),
    path('players/create/', create_player, name='player_create'),

    path('player_histories/', list_player_history, name='player_history_list'),
    path('player_histories/data_table/', login_required(PlayerHistoryListJson.as_view()), name='player_history_data_table'),
    path('player_histories/delete/<item_id>/', delete_player_history, name='player_history_delete'),


    path('referees/', list_referee, name='referee_list'),
    path('referees/data_table/', login_required(RefereeListJson.as_view()), name='referee_data_table'),
    path('referees/edit/<item_id>/', edit_referee, name='referee_edit'),
    path('referees/delete/<item_id>/', delete_referee, name='referee_delete'),
    path('referees/create/', create_referee, name='referee_create'),

    path('coaches/', list_coach, name='coach_list'),
    path('coaches/data_table/', login_required(CoachListJson.as_view()), name='coach_data_table'),
    path('coaches/edit/<item_id>/', edit_coach, name='coach_edit'),
    path('coaches/delete/<item_id>/', delete_coach, name='coach_delete'),
    path('coaches/create/', create_coach, name='coach_create'),

    path('coach_histories/', list_coach_history, name='coach_history_list'),
    path('coach_histories/data_table/', login_required(CoachHistoryListJson.as_view()), name='coach_history_data_table'),
    path('coach_histories/delete/<item_id>/', delete_coach_history, name='coach_history_delete'),

    path('matches/', list_match, name='match_list'),
    path('matches/data_table/', login_required(MatchListJson.as_view()), name='match_data_table'),
    path('matches/edit/<item_id>/', edit_match, name='match_edit'),
    path('matches/delete/<item_id>/', delete_match, name='match_delete'),
    path('matches/create/', create_match, name='match_create'),

    path('match_details/', list_match_detail, name='match_detail_list'),
    path('match_details/data_table/', login_required(MatchDetailListJson.as_view()), name='match_detail_data_table'),
    path('match_details/edit/<item_id>/', edit_match_detail, name='match_detail_edit'),
    path('match_details/delete/<item_id>/', delete_match_detail, name='match_detail_delete'),
    path('match_details/create/', create_match_detail, name='match_detail_create'),


    path('match_actions/', list_match_action, name='match_action_list'),
    path('match_actions/data_table/', login_required(MatchActionListJson.as_view()), name='match_action_data_table'),
    path('match_actions/edit/<item_id>/', edit_match_action, name='match_action_edit'),
    path('match_actions/delete/<item_id>/', delete_match_action, name='match_action_delete'),
    path('match_actions/create/', create_match_action, name='match_action_create'),


    path('categories/', list_category, name='category_list'),
    path('categories/data_table/', login_required(CategoryListJson.as_view()), name='category_data_table'),
    path('categories/edit/<item_id>/', edit_category, name='category_edit'),
    path('categories/delete/<item_id>/', delete_category, name='category_delete'),
    path('categories/create/', create_category, name='category_create'),

    path('posts/', list_post, name='post_list'),
    path('posts/data_table/', login_required(PostListJson.as_view()), name='post_data_table'),
    path('posts/edit/<item_id>/', edit_post, name='post_edit'),
    path('posts/delete/<item_id>/', delete_post, name='post_delete'),
    path('posts/create/', create_post, name='post_create'),

    path('banners/', list_banner, name='banner_list'),
    path('banners/data_table/', login_required(BannerListJson.as_view()), name='banner_data_table'),
    path('banners/edit/<item_id>/', edit_banner, name='banner_edit'),
    path('banners/delete/<item_id>/', delete_banner, name='banner_delete'),
    path('banners/create/', create_banner, name='banner_create'),

    path('banner_positions/', list_banner_position, name='banner_position_list'),
    path('banner_positions/data_table/', login_required(BannerPositionListJson.as_view()), name='banner_position_data_table'),
    path('banner_positions/edit/<item_id>/', edit_banner_position, name='banner_position_edit'),
    path('banner_positions/delete/<item_id>/', delete_banner_position, name='banner_position_delete'),
    path('banner_positions/create/', create_banner_position, name='banner_position_create'),

    path('galleries/', list_gallery, name='gallery_list'),
    path('galleries/data_table/', login_required(GalleryListJson.as_view()), name='gallery_data_table'),
    path('galleries/edit/<item_id>/', edit_gallery, name='gallery_edit'),
    path('galleries/delete/<item_id>/', delete_gallery, name='gallery_delete'),
    path('galleries/create/', create_gallery, name='gallery_create'),

    path('sponsors/', list_sponsor, name='sponsor_list'),
    path('sponsors/data_table/', login_required(SponsorListJson.as_view()), name='sponsor_data_table'),
    path('sponsors/edit/<item_id>/', edit_sponsor, name='sponsor_edit'),
    path('sponsors/delete/<item_id>/', delete_sponsor, name='sponsor_delete'),
    path('sponsors/create/', create_sponsor, name='sponsor_create'),

    path('socials/', list_social, name='social_list'),
    path('socials/data_table/', login_required(SocialListJson.as_view()), name='social_data_table'),
    path('socials/edit/<item_id>/', edit_social, name='social_edit'),
    path('socials/delete/<item_id>/', delete_social, name='social_delete'),
    path('socials/create/', create_social, name='social_create'),

]

frontend/urls.py
from django.conf.urls import url
from frontend.views import *

app_name = "frontend"

_logger = logging.getLogger('default')


def debug(msg):
    _logger.info('Application log : %s', msg)


urlpatterns = [
    url(r'^$', index, name='index'),

    url(r'^news/(?P<slug>[\w-]+)\.html$', news_detail, name='news_detail'),
    url(r'^clubs/(?P<slug>[\w-]+)\.html$', clubs_detail, name='clubs_detail'),
    url(r'^galleries/(?P<slug>[\w-]+)\.html$', galleries_detail, name='galleries_detail'),
    url(r'^match/(?P<id>\d+)$', match_detail, name='match_detail'),
    url(r'^player/(?P<item_id>\d+)$', player_detail, name='player_detail'),

    url(r'^news$', news, name='news'),
    url(r'^results$', results, name='results'),
    url(r'^fixtures$', fixtures, name='fixtures'),
    url(r'^tables$', tables, name='tables'),
    url(r'^clubs$', clubs, name='clubs'),
    url(r'^players$', players, name='players'),
    url(r'^managers$', managers, name='managers'),
    url(r'^galleries$', galleries, name='galleries'),
    url(r'^reload$', reload, name='reload'),



]

project/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from filebrowser.sites import site

from project import settings

urlpatterns = [
    path('select2/', include('django_select2.urls')),
    path('admin/filebrowser/', site.urls),
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('ckeditor/', include('core.ckeditor_uploader')),
    path('admin/', admin.site.urls),
    path('chaining/', include('smart_selects.urls')),
    path('core/', include('core.urls')),
    path('', include('frontend.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/templates/old_frontend/base.html
{% load static i18n %}
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Lao Premier League">
    <meta name="keywords" content="Lao Premier League">
    <meta name="author" content="Lao Premier League">
    <title>Lao Premier League - Homepage</title>
    <link rel="stylesheet" type="text/css" href="{% static "frontend/css/bootstrap.css" %}" media="all">
    <link rel="stylesheet" type="text/css" href="{% static "frontend/css/style.css" %}" media="all">
    <link rel="stylesheet" type="text/css" href="{% static "frontend/css/font-awesome.min.css" %}" media="all">
    <link href='//fonts.googleapis.com/css?family=Poppins:300,400,600,400i,700' rel='stylesheet' type='text/css'>


    <!-- Owl Stylesheets -->
    <link rel="stylesheet" href="{% static "frontend/js/owlcarousel/assets/owl.carousel.min.css" %}">
    <link rel="stylesheet" href="{% static "frontend/js/owlcarousel/assets/owl.theme.default.min.css" %}">


    <!--[if lt IE 9]>
        <script src="{% static "frontend/css/respond.min.js" %}"></script>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->


</head>

<body>

{% include 'frontend/partials/header.html' %}


{% block content %}

{% endblock %}

{% include 'frontend/partials/footer.html' %}


<div id="top">
    <a href="#" class="scrollup"><i class="fa fa-angle-double-up"></i></a>
</div>

<script src="{% static "frontend/js/jquery.min.js" %}"> </script>

<script src="{% static "frontend/js/bootstrap.min.js" %}"> </script>

<script src="{% static "frontend/js/myscript.js" %}"></script>

<script src="{% static "frontend/js/owlcarousel/owl.carousel.js" %}"></script>
<script src="{% static "frontend/js/owl.rows.js" %}"></script>

<!-- vendors -->
<script src="{% static "frontend/js/vendors/highlight.js" %}"></script>
<script src="{% static "frontend/js/app.js" %}"></script>

<script>
    $(document).ready(function() {
        var owl = $('#brands-carousel');
        owl.owlCarousel({
            margin: 10,
            nav: true,
            loop: true,
            dots:false,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        })
    })
</script>
<script type="text/javascript">
    $(document).ready(function() {
        var owl = $('#clubs-carousel');
        owl.owlCarousel({
            margin: 10,
            nav: true,
            loop: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items:4
                },
                1000: {
                    items: 8,
                    nav:false
                }
            }
        })
    })
</script>

<script>
    $(document).ready(function() {
        var owl = $('#matchweek-carousel');
        owl.owlCarousel({
            margin: 10,
            nav: true,
            loop: true,
            dots:false,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                991: {
                    items: 3
                },
                1000: {
                    items: 4,
                }
            }
        })
    })
</script>

<script>
    $(document).ready(function() {
        var owl = $('#news-carousel');
        owl.owlCarousel({
            margin: 0,
            nav: true,
            loop: true,
            nav:false,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items:1
                },
                1000: {
                    items: 1
                }
            }
        })
    })
</script>
<script>
    $(document).ready(function() {
        var owl = $('#news02-carousel');
        owl.owlCarousel({
            margin: 20,
            loop: true,
            nav:false,
            dots:false,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 3
                }
            }
        })
    })
</script>
<script>
    $(document).ready(function() {
        var owl = $('#news03-carousel');
        owl.owlCarousel({
            margin: 20,
            loop: true,
            nav:false,
            rows: true,
            rowsCount: 2,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 2
                }
            }
        })
    })
</script>

<script>
    $(document).ready(function() {
        var owl = $('#matchweek-carousel02');
        owl.owlCarousel({
            margin: 10,
            nav: true,
            loop: true,
            dots:false,
            responsiveClass:true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                991: {
                    items: 3
                },
                1000: {
                    items: 4,
                }
            }
        })
    })
</script>
{% block frontend_script %}

{% endblock %}
</body>
</html>

frontend/templates/old_frontend/clubs.html
{% extends 'frontend/base.html' %}
{% load staticfiles i18n thumbnail core_helper %}

{% block content %}
    <!-- start of breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <h3> Clubs </h3>
            <ul>
                <li> <i class="fa fa-home"> </i> </li>
                <li> <i class="fa fa-arrow-right"> </i> Clubs </li>
            </ul>

        </div>
    </div>

    <!-- Main content homepage -->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <!-- start left column -->
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <form id="club_filter">
                        <div class="block block-search-filter">
                            <div class="row">
                                <div class="col-md-4 col-sm-8 col-xs-12">
                                    <label> Filter by Season</label>
                                    <select name="season">
                                        {% for season in seasons %}
                                            <option {% if request.GET.season == season.id|slugify %}selected{% endif %} value="{{ season.id }}">{{ season.name }}</option>
                                        {% endfor %}
                                    </select>
                                </div>


                                <div class="col-md-4 col-sm-4 col-xs-12">
                                    <button id="club_filter_submit" class="btn"> Reset Filters </button>
                                </div>
                            </div>
                        </div>
                    </form>

                    <div class="list-season">

                        {% for club in list_clubs %}
                           <div class="col-md-3 col-sm-6 col-xs-12">
                            <div class="season-item">
                                <div class="content blue">
                                    <div class="name"><a href="{% url 'frontend:clubs_detail' club.slug %}">{{ club.name }}</a></div>
                                    <div class="season"> <img src="{% static 'frontend/images/icon-season.png' %}" alt="icon" />  {{ club.stadium.name }}</div>
                                    <div class="link-club">
                                        Club Profile
                                        <i class="fa fa-arrow-right"> </i>
                                    </div>
                                    <div class="club-logo image-radius">
                                        <a href="{% url 'frontend:clubs_detail' club.slug %}">
                                        {% thumbnail club.image "42x40" crop="center" as im %}
                                            <img class="responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ club.name }}">
                                        {% endthumbnail %}
                                        </a>
                                    </div>
                                </div>
                                <div class="image">
                                    <img src="{% static 'frontend/images/season-image.jpg' %}" alt="club01" />
                                </div>
                            </div>
                        </div>

                        {% endfor %}


                    </div>

                </div>

                {% right_content %}
            </div>
        </div>
    </div>
{% endblock %}

{% block frontend_script %}
    {{ super }}
    <script>
       $(function(){
           var divs = $(".list-season > div");
           for(let i = 0; i < divs.length; i+=4) {
               divs.slice(i, i+4).wrapAll("<div class='row'></div>");
           }
       })
    </script>
    <script>
        $(function(){
            $('#club_filter_submit').click(function(){
                $('#club_filter').submit()
            });
        });
    </script>
{% endblock %}

frontend/templates/old_frontend/galleries.html
{% extends 'frontend/base.html' %}
{% load staticfiles i18n thumbnail core_helper %}

{% block content %}
    <!-- start of breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <h3>  Media Gallery </h3>
            <ul>
                <li> <i class="fa fa-home"> </i> </li>
                <li> <i class="fa fa-arrow-right"> </i> Media Gallery </li>
            </ul>

        </div>
    </div>

    <!-- Main content homepage -->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <!-- start left column -->
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="news-list">
                        <!-- start item -->

                        {% for gallery in list_galleries %}
                            <div class="news-item style-v2">
                            <div class="images">
                                <a href="{% url 'frontend:galleries_detail' gallery.slug %}">
                                    {% thumbnail gallery.image "313x209" crop="center" as im %}
                                        <img class="responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ gallery.name }}">
                                    {% endthumbnail %}
                                </a>
                            </div>
                            <div class="new-content">
                                <div class="news-name"> <a href="{% url 'frontend:galleries_detail' gallery.slug %}">{{ gallery.name }} </a></div>
                            </div>
                        </div>
                        {% endfor %}


                        <!-- start button -->
                        {% comment %}<div class="text-center">
                            <button class="btn load-more"> <span> Loading more content...</span></button>
                        </div>{% endcomment %}

                    </div>


                        {% for banner in banners %}
                            <!-- 2. start block banner  -->
                            <div class="block block-banner">
                                <a target="_blank" href="{{ banner.link }}"><img src="{{ banner.image.url }}" alt="" class=""></a>
                            </div>

                        {% endfor %}

                </div>

                {% right_content %}
            </div>
        </div>
    </div>
{% endblock %}

frontend/templates/old_frontend/galleries_detail.html
{% extends 'frontend/base.html' %}
{% load staticfiles i18n thumbnail core_helper %}

{% block content %}


    <!-- start of breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <h3> News </h3>
            <ul>
                <li> <i class="fa fa-home"> </i> </li>
                <li> <i class="fa fa-arrow-right"> </i> Media Gallery </li>
                <li> <i class="fa fa-arrow-right"> </i> {{ gallery.name }} </li>
            </ul>

        </div>
    </div>

    <div class="main-content">
        <div class="container">
            <div class="row">

                <!-- start left column -->
                <div class="col-md-9 col-sm-12 col-xs-12">

                <div>
                    <img class="responsive" src="{{ gallery.image.url }}"  alt="{{ gallery.name }}">
                </div>

                    {% for banner in banners %}
                        <!-- 2. start block banner  -->
                        <div class="block block-banner">
                            <a target="_blank" href="{{ banner.link }}"><img src="{{ banner.image.url }}" alt="" class=""></a>
                        </div>

                    {% endfor %}

                </div>

                {% right_content %}
            </div>
        </div>
    </div>

{% endblock %}

frontend/templates/old_frontend/index.html
{% extends 'frontend/base.html' %}
{% load staticfiles i18n thumbnail core_helper %}

{% block content %}
    <!-- Start content homepage -->
    <section class="wrapper">
        <div class="row-matchweek">
            <div class="container">
                <div class="block block-matchweek">
                    <div class="block-title"><span>Fixtures</span></div>
                    <div class="block-content">
                        <!-- Start matchweek-carousel -->
                        <div class="owl-carousel owl-theme" id="matchweek-carousel">
                            {% for match_this_week in match_this_weeks %}
                                <div class="item">
                                <div class="matchweek-item">
                                    <div class="matchweek-content">
                                        <span class="time">{{ match_this_week.start_time|date:'D d M' }}</span>
                                        <span class="match-detail">
                                             <span class="team">
                                                 {% thumbnail match_this_week.home_team.image "42x40" crop="center" as im %}
                                                     <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ match_this_week.home_team.name }}">
                                                 {% endthumbnail %}

                                                 <span class="team-name"> {{ match_this_week.home_team.name }} </span>
                                           </span>
                                           <span class="result-match"> {{ match_this_week.home_end_score }} - {{ match_this_week.away_end_score }} </span>
                                           <span class="team">
                                                  {% thumbnail match_this_week.away_team.image "42x40" crop="center" as im %}
                                                      <img src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ match_this_week.away_team.name }}">
                                                  {% endthumbnail %}
                                                 <span class="team-name"> {{ match_this_week.away_team.name }} </span>
                                           </span>
                                     </span>
                                    </div>
                                    <div class="matchweek-link">
                                        <a href="{% url 'frontend:fixtures' %}"> Start </a>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <!-- Main content homepage -->
        <div class="main-content-homepage">
            <div class="container">
                <div class="row">
                    <!-- start left column -->
                    {% include "frontend/partials/main_index.html" %}

                    <!-- start right column -->

                    {% right_content %}

                </div>
            </div>
        </div>
    </section>
{% endblock %}

frontend/templates/old_frontend/news.html
{% extends 'frontend/base.html' %}
{% load staticfiles i18n thumbnail core_helper %}

{% block content %}
    <!-- start of breadcrumbs -->
    <div class="breadcrumbs">
        <div class="container">
            <h3> News </h3>
            <ul>
                <li> <i class="fa fa-home"> </i> </li>
                <li> <i class="fa fa-arrow-right"> </i> News </li>
            </ul>

            <ul class="menu-news pull-right">
                {% if active_category is not None %}
                    <li> <a href="{% url 'frontend:news' %}"> All </a> </li>
                {% else %}
                     <li> <a href="{% url 'frontend:news' %}" class="active"> All </a> </li>
                {% endif %}

                {% for category in categories %}
                    {% if category.id == active_category.id %}
                        <li> <a href="{% url 'frontend:news' %}?category={{ category.slug }}" class="active"> {{ category.name }} </a> </li>
                    {% else %}
                        <li> <a href="{% url 'frontend:news' %}?category={{ category.slug }}"> {{ category.name }} </a> </li>
                    {% endif %}
                {% endfor %}

            </ul>
        </div>
    </div>

    <!-- Main content homepage -->
    <div class="main-content">
        <div class="container">
            <div class="row">
                <!-- start left column -->
                <div class="col-md-9 col-sm-12 col-xs-12">
                    <div class="news-list">
                        <!-- start item -->

                        {% for post in posts %}
                            <div class="news-item style-v2">
                            <div class="images">
                                <a href="{% url 'frontend:news_detail' post.slug %}">
                                    {% thumbnail post.image "313x209" crop="center" as im %}
                                        <img class="responsive" src="{{ im.url }}" width="{{ im.width }}" height="{{ im.height }}" alt="{{ post.name }}">
                                    {% endthumbnail %}
                                </a>
                            </div>
                            <div class="new-content">
                                <div class="news-name"> <a href="{% url 'frontend:news_detail' post.slug %}">{{ post.name }} </a></div>
                                <div class="news-des">
                                    {{ post.desc }}
                                </div>
                            </div>
                        </div>
                        {% endfor %}


                        <!-- start button -->
                        {% comment %}<div class="text-center">
                            <button class="btn load-more"> <span> Loading more content...</span></button>
                        </div>{% endcomment %}

                    </div>


                        {% for banner in banners %}
                            <!-- 2. start block banner  -->
                            <div class="block block-banner">
                                <a target="_blank" href="{{ banner.link }}"><img src="{{ banner.image.url }}" alt="" class=""></a>
                            </div>

                        {% endfor %}

                </div>

                {% right_content %}
            </div>
        </div>
    </div>
{% endblock %}